name = "lastfm-proxy-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
ENVIRONMENT = "production"
LASTFM_API_BASE_URL = "http://ws.audioscrobbler.com/2.0/"

[[kv_namespaces]]
binding = "CACHE"
id = "a60277c81ae147d5a8f028f9b701ce63"
preview_id = "e60e61f503ea4fde87b7624f6029a0b9"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "ce2a522e723542cda892659f3e3a5b67"
preview_id = "0102b8f6b3f34539a66799c393256ae6"

[env.preview]
vars = { ENVIRONMENT = "preview" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

[observability]
enabled = true